logging:
  level:
    org.springframework: INFO
    com.github.mayconr.juoserver: INFO
    com.github.mayconr.juoserver.game.core: INFO
    com.github.mayconr.juoserver.infrastructure.server: INFO
    com.github.mayconr.juoserver.network: DEBUG
    com.github.mayconr.juoserver.game.session.player.vitals: INFO
    com.github.mayconr.juoserver.game.session.player.skill: DEBUG

server:
  mobile:
    backpack: backpack
  vitals:
    saturationFactor: 100
  gameLoop:
    tps: 20
  skills:
    minGainChance: 0
    maxGainChance: 0.5 # 50%
    balanceOffset: 50
    cap: 100
  world:
    lightOfSight: 24
