package com.github.mayconr.juoserver.infrastructure.storage.mobile;

import com.github.mayconr.juoserver.common.template.NpcTemplate;
import com.github.mayconr.juoserver.game.model.*;

import java.util.UUID;

public class MobileFactory {

    public static UOPlayer createNewPlayer(PlayerDetails details) {
        return new UOPlayer(new UOMobile(
                UUID.randomUUID(),
                -1,
                0x190,
                2514,
                550,
                0,
                details.name(),
                Direction.NORTH,
                0x83EA,
                CharacterStatus.NORMAL,
                Notoriety.INNOCENT,
                false,
                Race.HUMAN,
                Gender.MALE,
                80,
                100,
                50,
                50,
                100,
                50,
                100,
                50,
                100,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
        ), details.account().getId());
    }

    public static UONpc createFromTemplate(NpcTemplate template, Location location) {
        final var npc = new UONpc(new UOMobile(
                UUID.randomUUID(),
                -1,
                template.modelId(),
                location.getX(),
                location.getY(),
                location.getZ(),
                template.name(),
                Direction.NORTH,
                template.hue(),
                CharacterStatus.NORMAL,
                template.notoriety(),
                false,
                Race.HUMAN,
                Gender.MALE,
                80,
                100,
                50,
                50,
                100,
                50,
                100,
                50,
                100,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
        ), template.type(), template.ai());
        npc.setMount((String) template.attrMap().get("mount"));
        return npc;
    }
}
