package com.github.mayconr.juoserver.game.session.world;

import com.github.mayconr.juoserver.common.template.NpcTemplate;
import com.github.mayconr.juoserver.game.model.*;

import java.util.Collections;
import java.util.UUID;

public class MobileFactory {

    public static UOPlayer createNewPlayer(SerialGenerator serialGenerator, PlayerDetails details) {
        final var player =  new UOPlayer(new UOMobile(
                UUID.randomUUID(),
                serialGenerator.nextMobileMobile(),
                0x190,
                2514,
                550,
                0,
                details.name(),
                details.name(),
                Collections.emptyMap(),
                Direction.NORTH,
                0x83EA,
                CharacterStatus.NORMAL,
                Notoriety.INNOCENT,
                false,
                Race.HUMAN,
                Gender.MALE,
                80,
                100,
                50,
                50,
                100,
                50,
                100,
                50,
                100,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
        ), details.account().getId());
        for (UOItem item : details.equipedItems()) {
            player.equipItem(item);
        }
        return player;
    }

    public static UONpc createNpcFromTemplate(SerialGenerator serialGenerator, NpcTemplate template, Location location) {
        return new UONpc(new UOMobile(
                UUID.randomUUID(),
                serialGenerator.nextMobileMobile(),
                template.modelId(),
                location.getX(),
                location.getY(),
                location.getZ(),
                template.name(),
                template.displayName(),
                template.attr(),
                Direction.NORTH,
                template.hue(),
                CharacterStatus.NORMAL,
                template.notoriety(),
                false,
                Race.HUMAN,
                Gender.MALE,
                80,
                100,
                50,
                50,
                100,
                50,
                100,
                50,
                100,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
        ), template.type(),
            template.ai(),
            template.mountItemName());
    }
}
